/* automatically generated from settings-dialog.ui */
#ifdef __SUNPRO_C
#pragma align 4 (settings_dialog_ui)
#endif
#ifdef __GNUC__
static const char settings_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char settings_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.14\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkAdjustment\" id=\"adjustment1\"><property name=\"lo"
  "wer\">5</property><property name=\"upper\">1000</property><property nam"
  "e=\"value\">5</property><property name=\"step_increment\">5</property><"
  "property name=\"page_increment\">10</property></object><object class=\""
  "GtkAdjustment\" id=\"adjustment2\"><property name=\"upper\">100</proper"
  "ty><property name=\"step_increment\">1</property><property name=\"page_"
  "increment\">10</property></object><object class=\"GtkImage\" id=\"image"
  "5\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"icon_name\">help-browser</property"
  "></object><object class=\"GtkImage\" id=\"image6\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"icon_name\">window-close-symbolic</property></object><obje"
  "ct class=\"XfceTitledDialog\" id=\"settings-dialog\"><property name=\"c"
  "an_focus\">False</property><property name=\"title\" translatable=\"yes\""
  ">Clipman Settings</property><property name=\"window_position\">center</"
  "property><property name=\"default_width\">340</property><property name="
  "\"default_height\">390</property><property name=\"destroy_with_parent\""
  ">True</property><property name=\"icon_name\">xfce4-clipman-plugin</prop"
  "erty><property name=\"type_hint\">dialog</property><child internal-chil"
  "d=\"vbox\"><object class=\"GtkBox\" id=\"settings-dialog-vbox\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"orientation\">vertical</property><property na"
  "me=\"spacing\">2</property><child internal-child=\"action_area\"><objec"
  "t class=\"GtkButtonBox\" id=\"settings-dialog-actionarea\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><child><object class=\"GtkButton\" id=\"settings-dialog-button-help"
  "\"><property name=\"label\" translatable=\"yes\">_Help</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">True</property><property n"
  "ame=\"image\">image5</property><property name=\"use_underline\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">0</pro"
  "perty><property name=\"secondary\">True</property></packing></child><ch"
  "ild><object class=\"GtkButton\" id=\"settings-dialog-button-close\"><pr"
  "operty name=\"label\" translatable=\"yes\">_Close</property><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"receives_default\">True</property><property name=\""
  "image\">image6</property><property name=\"use_underline\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkNotebook\" "
  "id=\"settings-dialog-notebook\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"border_"
  "width\">6</property><child><object class=\"GtkBox\" id=\"vbox-general\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">12</property><property"
  " name=\"orientation\">vertical</property><property name=\"spacing\">18<"
  "/property><child><object class=\"GtkFrame\" id=\"frame-behavior\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label_xalign\">0</property><property name=\""
  "shadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment-behavior\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"top_padding\">6</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkBox\" id=\"vbox-behavior\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"or"
  "ientation\">vertical</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkCheckButton\" id=\"add-selections\"><property "
  "name=\"label\" translatable=\"yes\">Sync mouse _selections</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"has_tooltip\">True</property><property name=\"tooltip_text\""
  " translatable=\"yes\">If checked, the selections will be synced with th"
  "e default clipboard in a way that you can paste what you select</proper"
  "ty><property name=\"use_underline\">True</property><property name=\"dra"
  "w_indicator\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkCh"
  "eckButton\" id=\"show-qr-code\"><property name=\"label\" translatable=\""
  "yes\">_QR-Code support</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">False</property><property name=\"has_tooltip\">True</prope"
  "rty><property name=\"tooltip_text\" translatable=\"yes\">If checked, th"
  "e menu shows a QR-Code of the currently selected clipboard entry</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"dr"
  "aw_indicator\">True</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child><child><object class=\"Gtk"
  "Box\" id=\"hbox1\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"tooltip_text\" tran"
  "slatable=\"yes\">Automatically paste a selected item from the history</"
  "property><property name=\"spacing\">4</property><child><object class=\""
  "GtkLabel\" id=\"label-paste-on-activate\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">_Paste instantly:</property><property "
  "name=\"use_underline\">True</property><property name=\"mnemonic_widget\""
  ">combobox-paste-on-activate</property><property name=\"xalign\">0</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkComboBoxText\" id=\"comb"
  "obox-paste-on-activate\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">1</property></packing></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">2</property></packing></child>"
  "</object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label-general\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">&lt;b&gt;General&lt;/b&gt;</property><property na"
  "me=\"use_markup\">True</property></object></child></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">False</p"
  "roperty><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkFrame\" id=\"frame-history\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label_xalign\">0</property><property name=\"shadow_type\">n"
  "one</property><child><object class=\"GtkAlignment\" id=\"alignment-hist"
  "ory\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"top_padding\">6</property><prope"
  "rty name=\"left_padding\">12</property><child><object class=\"GtkBox\" "
  "id=\"vbox-history\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"orientation\">vert"
  "ical</property><property name=\"spacing\">6</property><child><object cl"
  "ass=\"GtkCheckButton\" id=\"popup-at-pointer\"><property name=\"label\""
  " translatable=\"yes\">P_osition menu at mouse pointer</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">Popup the menu at the mouse p"
  "ointer position, only for the xfce4-popup-clipman command</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"draw_indi"
  "cator\">True</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkBox\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><child><object class=\"GtkLabel\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">Maximum items:</property><prop"
  "erty name=\"xalign\">0</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">True</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkSpinButton\" id=\"max-menu-items\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"a"
  "djustment\">adjustment2</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">True</property><property"
  " name=\"pack_type\">end</property><property name=\"position\">1</proper"
  "ty></packing></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child></object></child></object></child><"
  "child type=\"label\"><object class=\"GtkLabel\" id=\"label-menu\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Menu&"
  "lt;/b&gt;</property><property name=\"use_markup\">True</property></obje"
  "ct></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">1</"
  "property></packing></child></object></child><child type=\"tab\"><object"
  " class=\"GtkLabel\" id=\"label-behavior\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">_Behavior</property><property name=\"u"
  "se_underline\">True</property></object><packing><property name=\"tab_fi"
  "ll\">False</property></packing></child><child><object class=\"GtkBox\" "
  "id=\"vbox-actions\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"border_width\">12<"
  "/property><property name=\"orientation\">vertical</property><property n"
  "ame=\"spacing\">6</property><child><object class=\"GtkBox\" id=\"box1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><child><object class=\"GtkLabel\" id=\"label1\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">&lt;b&gt;_Enabl"
  "e automatic actions&lt;/b&gt;</property><property name=\"use_markup\">T"
  "rue</property><property name=\"use_underline\">True</property><property"
  " name=\"xalign\">0</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkSwit"
  "ch\" id=\"enable-actions\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"tooltip_text"
  "\" translatable=\"yes\">If checked, the clipboard texts will be matched"
  " against regular expressions and a menu will display possible actions a"
  "utomatically.\nOtherwise the menu will only appear when calling \"xfce4"
  "-popup-clipman-actions\" (and a match was found)</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkBox\" id=\"box-actions\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"margin_left\">12</property><property nam"
  "e=\"orientation\">vertical</property><child><object class=\"GtkRadioBut"
  "ton\" id=\"skip-action-1\"><property name=\"label\" translatable=\"yes\""
  ">_Show actions by holding Control</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">False</property><property name=\"tooltip_text\""
  " translatable=\"yes\">When the selection is done (mouse or keyboard) an"
  "d the Control key is still pressed down, the popup menu for matched act"
  "ions will be shown</property><property name=\"use_underline\">True</pro"
  "perty><property name=\"draw_indicator\">True</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkRadioButton\" id=\"skip-action-2\"><property "
  "name=\"label\" translatable=\"yes\">S_kip actions by holding Control</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">False</prope"
  "rty><property name=\"tooltip_text\" translatable=\"yes\">When the selec"
  "tion is done (mouse or keyboard) and the Control key is still pressed d"
  "own, the popup menu for matched actions will be skipped</property><prop"
  "erty name=\"use_underline\">True</property><property name=\"active\">Tr"
  "ue</property><property name=\"draw_indicator\">True</property><property"
  " name=\"group\">skip-action-1</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkBox\" id=\"hbox2\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"margin_t"
  "op\">12</property><property name=\"spacing\">6</property><child><object"
  " class=\"GtkScrolledWindow\" id=\"scrolledwindow1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"shadow_type\">in</property><child><object class=\"GtkTreeV"
  "iew\" id=\"actions\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"headers_visible\">"
  "False</property><property name=\"rules_hint\">True</property><child int"
  "ernal-child=\"selection\"><object class=\"GtkTreeSelection\" id=\"treev"
  "iew-selection1\"/></child></object></child></object><packing><property "
  "name=\"expand\">True</property><property name=\"fill\">True</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkBox\" id=\"vbox4\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"orienta"
  "tion\">vertical</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkButton\" id=\"button-add-action\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"toolt"
  "ip_text\" translatable=\"yes\">Add action</property><child><object clas"
  "s=\"GtkImage\" id=\"image1\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"icon_name"
  "\">list-add-symbolic</property><property name=\"icon_size\">1</property"
  "></object></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkButton\" id"
  "=\"button-edit-action\"><property name=\"visible\">True</property><prop"
  "erty name=\"sensitive\">False</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">True</property><proper"
  "ty name=\"tooltip_text\" translatable=\"yes\">Edit action</property><ch"
  "ild><object class=\"GtkImage\" id=\"image2\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"icon_name\">document-edit-symbolic</property><property name=\"ic"
  "on_size\">1</property></object></child></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">1</property></packing></child><child><object c"
  "lass=\"GtkButton\" id=\"button-delete-action\"><property name=\"visible"
  "\">True</property><property name=\"sensitive\">False</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">True</property><property name=\"tooltip_text\" translatable=\"yes\">De"
  "lete action</property><child><object class=\"GtkImage\" id=\"image3\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"icon_name\">edit-delete-symbolic</prope"
  "rty><property name=\"icon_size\">1</property></object></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">False</property><property name=\"position\">2</property></packing><"
  "/child><child><object class=\"GtkButton\" id=\"button-reset-actions\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">True</property><prope"
  "rty name=\"tooltip_text\" translatable=\"yes\">Reset all actions to the"
  " system default values</property><child><object class=\"GtkImage\" id=\""
  "image4\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"icon_name\">edit-clear-symbol"
  "ic</property><property name=\"icon_size\">1</property></object></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"pack_type\">end</property"
  "><property name=\"position\">3</property></packing></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">2</property>"
  "</packing></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">1</property></packing></child></object><packing><property name=\"pos"
  "ition\">1</property></packing></child><child type=\"tab\"><object class"
  "=\"GtkLabel\" id=\"label-actions\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">_Actions</property><property name=\"use_under"
  "line\">True</property></object><packing><property name=\"position\">1</"
  "property><property name=\"tab_fill\">False</property></packing></child>"
  "<child><object class=\"GtkBox\" id=\"vbox-tweaks\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"border_width\">12</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">6</property><child><obje"
  "ct class=\"GtkBox\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><child><object class=\"GtkLabel\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;R"
  "emember history&lt;/b&gt;</property><property name=\"use_markup\">True<"
  "/property><property name=\"xalign\">0</property></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkSwitch\" id=\"save-on-quit\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkBox\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"margin_left\">12</property><property name=\"orientation\">v"
  "ertical</property><property name=\"spacing\">6</property><child><object"
  " class=\"GtkCheckButton\" id=\"store-an-image\"><property name=\"label\""
  " translatable=\"yes\">Remember last copied _image</property><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"receives_default\">False</property><property name="
  "\"tooltip_text\" translatable=\"yes\">If checked, this option allows on"
  "e to store one image inside the history</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkCheckButton\" id=\"reorde"
  "r-items\"><property name=\"label\" translatable=\"yes\">_Reorder histor"
  "y items</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Fa"
  "lse</property><property name=\"tooltip_text\" translatable=\"yes\">Push"
  " last copied text to the top of the history, useful to reorder old item"
  "s</property><property name=\"use_underline\">True</property><property n"
  "ame=\"draw_indicator\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"position\">1</property></packing></child><child><object cl"
  "ass=\"GtkCheckButton\" id=\"reverse-order\"><property name=\"label\" tr"
  "anslatable=\"yes\">Re_verse history order</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">False</property><property name=\"toolti"
  "p_text\" translatable=\"yes\">Reverse order of the history shown in the"
  " menu</property><property name=\"use_underline\">True</property><proper"
  "ty name=\"draw_indicator\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">2</property></packing></child><child><objec"
  "t class=\"GtkCheckButton\" id=\"history-ignore-selections\"><property n"
  "ame=\"label\" translatable=\"yes\">Ignore mouse s_elections</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"has_tooltip\">True</property><property name=\"tooltip_text\""
  " translatable=\"yes\">If checked, the selections won\'t affect the hist"
  "ory except the manual copies</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">3</property></packing"
  "></child><child><object class=\"GtkBox\" id=\"hbox-history-size\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"spacing\">4</property><child><object class="
  "\"GtkLabel\" id=\"label-history-size\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">Size of the _history:</property><property "
  "name=\"use_underline\">True</property><property name=\"mnemonic_widget\""
  ">max-texts-in-history</property><property name=\"xalign\">0</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkSpinButton\" id=\"max-texts-in"
  "-history\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"invisible_char\">\342\200\242"
  "</property><property name=\"text\" translatable=\"yes\">5</property><pr"
  "operty name=\"adjustment\">adjustment1</property><property name=\"value"
  "\">100</property></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"pack_type"
  "\">end</property><property name=\"position\">1</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">4</property"
  "></packing></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">6</property></packing></child></object><packing><property name=\"po"
  "sition\">2</property></packing></child><child type=\"tab\"><object clas"
  "s=\"GtkLabel\" id=\"label-histor\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">H_istory</property><property name=\"use_under"
  "line\">True</property></object><packing><property name=\"position\">2</"
  "property><property name=\"tab_fill\">False</property></packing></child>"
  "</object><packing><property name=\"expand\">True</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child></object></child><action-widgets><action-widget response="
  "\"2\">settings-dialog-button-help</action-widget><action-widget respons"
  "e=\"0\">settings-dialog-button-close</action-widget></action-widgets></"
  "object><object class=\"GtkDialog\" id=\"action-dialog\"><property name="
  "\"can_focus\">False</property><property name=\"title\" translatable=\"y"
  "es\">Edit Action</property><property name=\"modal\">True</property><pro"
  "perty name=\"window_position\">center-on-parent</property><property nam"
  "e=\"default_width\">400</property><property name=\"default_height\">440"
  "</property><property name=\"destroy_with_parent\">True</property><prope"
  "rty name=\"icon_name\">system-run</property><property name=\"type_hint\""
  ">dialog</property><property name=\"skip_taskbar_hint\">True</property><"
  "property name=\"transient_for\">settings-dialog</property><child><place"
  "holder/></child><child internal-child=\"vbox\"><object class=\"GtkBox\""
  " id=\"action-dialog-vbox\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"orientation"
  "\">vertical</property><property name=\"spacing\">6</property><child int"
  "ernal-child=\"action_area\"><object class=\"GtkButtonBox\" id=\"action-"
  "dialog-actionarea\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"layout_style\">end"
  "</property><child><object class=\"GtkButton\" id=\"action-dialog-button"
  "-cancel\"><property name=\"label\">_Cancel</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">True</property><property name=\"use_un"
  "derline\">True</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">False</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkButt"
  "on\" id=\"action-dialog-button-ok\"><property name=\"label\">_OK</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">True</property><"
  "property name=\"use_underline\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">False</property><property name=\"pack_type\">end</property><proper"
  "ty name=\"position\">0</property></packing></child><child><object class"
  "=\"GtkBox\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"border_width\">6</property"
  "><property name=\"orientation\">vertical</property><property name=\"spa"
  "cing\">18</property><child><object class=\"GtkFrame\" id=\"frame-action"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label_xalign\">0</property><propert"
  "y name=\"shadow_type\">none</property><child><object class=\"GtkAlignme"
  "nt\" id=\"alignment-action\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"top_paddi"
  "ng\">6</property><property name=\"left_padding\">12</property><child><o"
  "bject class=\"GtkBox\" id=\"box2\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"ori"
  "entation\">vertical</property><property name=\"spacing\">6</property><c"
  "hild><object class=\"GtkGrid\" id=\"grid1\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"row_spacing\">6</property><property name=\"column_spacing\">12</p"
  "roperty><property name=\"row_homogeneous\">True</property><child><objec"
  "t class=\"GtkEntry\" id=\"action-name\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "hexpand\">True</property><property name=\"invisible_char\">\342\200\242"
  "</property></object><packing><property name=\"left_attach\">1</property"
  "><property name=\"top_attach\">0</property><property name=\"width\">2</"
  "property></packing></child><child><object class=\"GtkLabel\" id=\"label"
  "-action-name\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Name:</property><property name=\"xalign\">0</property></object><p"
  "acking><property name=\"left_attach\">0</property><property name=\"top_"
  "attach\">0</property></packing></child><child><object class=\"GtkLabel\""
  " id=\"label-action-pattern\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label\" t"
  "ranslatable=\"yes\">Pattern:</property><property name=\"xalign\">0</pro"
  "perty></object><packing><property name=\"left_attach\">0</property><pro"
  "perty name=\"top_attach\">1</property></packing></child><child><object "
  "class=\"GtkEntry\" id=\"regex\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"hexpand"
  "\">True</property><property name=\"invisible_char\">\342\200\242</prope"
  "rty></object><packing><property name=\"left_attach\">1</property><prope"
  "rty name=\"top_attach\">1</property></packing></child><child><object cl"
  "ass=\"GtkButton\" id=\"button-action-pattern\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">True</property><property name=\"halign\">cen"
  "ter</property><child><object class=\"GtkImage\" id=\"image-action-patte"
  "rn\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"icon_name\">document-edit-symboli"
  "c</property><property name=\"icon_size\">1</property></object></child><"
  "/object><packing><property name=\"left_attach\">2</property><property n"
  "ame=\"top_attach\">1</property></packing></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">0</property></packing></child><child"
  "><object class=\"GtkInfoBar\" id=\"regex-infobar\"><property name=\"can"
  "_focus\">False</property><property name=\"revealed\">False</property><c"
  "hild internal-child=\"action_area\"><object class=\"GtkButtonBox\"><pro"
  "perty name=\"can_focus\">False</property><property name=\"spacing\">6</"
  "property><property name=\"layout_style\">end</property><child><placehol"
  "der/></child></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">0"
  "</property></packing></child><child internal-child=\"content_area\"><ob"
  "ject class=\"GtkBox\"><property name=\"can_focus\">False</property><pro"
  "perty name=\"spacing\">16</property><child><object class=\"GtkImage\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"icon_name\">dialog-information-symbolic"
  "</property><property name=\"icon_size\">3</property></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">True</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkLabel\" id=\"label-regex-info\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">You can use the substituti"
  "on parameters \"\\1\", \"\\2\" and so on in the commands. The parameter"
  " \"\\0\" represents the complete text. The pattern is always anchored w"
  "ithin the special characters ^$</property><property name=\"wrap\">True<"
  "/property><property name=\"xalign\">0</property></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">2</property></packing></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">False</property><property name=\"position\">0</property></packing><"
  "/child></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"manua"
  "l\"><property name=\"label\" translatable=\"yes\">Activate only on manu"
  "al copy</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Fa"
  "lse</property><property name=\"has_tooltip\">True</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">By default the action is trig"
  "gered by a selection, check this option to trigger the action only when"
  " you make a manual copy</property><property name=\"draw_indicator\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">2</"
  "property></packing></child></object></child></object></child><child typ"
  "e=\"label\"><object class=\"GtkLabel\" id=\"label-action\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Action&lt;/b"
  "&gt;</property><property name=\"use_markup\">True</property></object></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">1</prope"
  "rty></packing></child><child><object class=\"GtkFrame\" id=\"frame-comm"
  "ands\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label_xalign\">0</property><pro"
  "perty name=\"shadow_type\">none</property><child><object class=\"GtkAli"
  "gnment\" id=\"alignment-commands\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"top"
  "_padding\">6</property><property name=\"left_padding\">12</property><ch"
  "ild><object class=\"GtkBox\" id=\"hbox-commands\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"spacing\">6</property><child><object class=\"GtkBox\" id=\""
  "vbox-commands\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"orientation\">vertical"
  "</property><property name=\"spacing\">6</property><child><object class="
  "\"GtkGrid\" id=\"grid2\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"row_spacing\""
  ">6</property><property name=\"column_spacing\">6</property><property na"
  "me=\"row_homogeneous\">True</property><child><object class=\"GtkEntry\""
  " id=\"command-name\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"hexpand\">True</pr"
  "operty><property name=\"invisible_char\">\342\200\242</property></objec"
  "t><packing><property name=\"left_attach\">1</property><property name=\""
  "top_attach\">0</property></packing></child><child><object class=\"GtkEn"
  "try\" id=\"command\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"hexpand\">True</pr"
  "operty><property name=\"invisible_char\">\342\200\242</property></objec"
  "t><packing><property name=\"left_attach\">1</property><property name=\""
  "top_attach\">1</property></packing></child><child><object class=\"GtkLa"
  "bel\" id=\"label-command\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\">Command:</property><property name=\"xalign\">0</prope"
  "rty></object><packing><property name=\"left_attach\">0</property><prope"
  "rty name=\"top_attach\">1</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"label-command-name\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\">Name:</property><property name=\"xali"
  "gn\">0</property></object><packing><property name=\"left_attach\">0</pr"
  "operty><property name=\"top_attach\">0</property></packing></child></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">0</property></pack"
  "ing></child><child><object class=\"GtkScrolledWindow\" id=\"scrolledwin"
  "dow-commands\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"shadow_type\">in</proper"
  "ty><child><object class=\"GtkTreeView\" id=\"commands\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"hexpand\">True</property><property name=\"headers_visi"
  "ble\">False</property><property name=\"rules_hint\">True</property><chi"
  "ld internal-child=\"selection\"><object class=\"GtkTreeSelection\"/></c"
  "hild></object></child></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">2</property></packing></child></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkBox\" id=\"vbox-command-buttons\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "orientation\">vertical</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkButton\" id=\"button-add-command\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">True</property><child><object"
  " class=\"GtkImage\" id=\"image-add-command\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"icon_name\">list-add-symbolic</property><property name=\"icon_si"
  "ze\">1</property></object></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkButton\" id=\"button-refresh-command\"><property name=\"visible\">"
  "True</property><property name=\"sensitive\">False</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Tr"
  "ue</property><child><object class=\"GtkImage\" id=\"image-refresh-comma"
  "nd\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"icon_name\">document-save-symboli"
  "c</property><property name=\"icon_size\">1</property></object></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">1</property></p"
  "acking></child><child><object class=\"GtkButton\" id=\"button-delete-co"
  "mmand\"><property name=\"visible\">True</property><property name=\"sens"
  "itive\">False</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">True</property><child><object class=\""
  "GtkImage\" id=\"image-delete-command\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "icon_name\">edit-delete-symbolic</property><property name=\"icon_size\""
  ">1</property></object></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">2</property></packing></child></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "</child></object></child><child type=\"label\"><object class=\"GtkLabel"
  "\" id=\"label-commands\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">&lt;b&gt;Commands&lt;/b&gt;</property><property name=\""
  "use_markup\">True</property></object></child></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">2</property></packing></child></object><pa"
  "cking><property name=\"expand\">True</property><property name=\"fill\">"
  "True</property><property name=\"position\">1</property></packing></chil"
  "d></object></child><action-widgets><action-widget response=\"0\">action"
  "-dialog-button-cancel</action-widget><action-widget response=\"1\">acti"
  "on-dialog-button-ok</action-widget></action-widgets></object><object cl"
  "ass=\"GtkTextBuffer\" id=\"textbuffer1\"><property name=\"text\" transl"
  "atable=\"yes\">Type here your custom text, for example a URL, a filenam"
  "e, etc.</property></object><object class=\"GtkDialog\" id=\"regex-dialo"
  "g\"><property name=\"can_focus\">False</property><property name=\"title"
  "\" translatable=\"yes\">Regular expression</property><property name=\"m"
  "odal\">True</property><property name=\"default_width\">260</property><p"
  "roperty name=\"default_height\">260</property><property name=\"destroy_"
  "with_parent\">True</property><property name=\"icon_name\">gtk-edit</pro"
  "perty><property name=\"type_hint\">dialog</property><property name=\"sk"
  "ip_taskbar_hint\">True</property><property name=\"transient_for\">actio"
  "n-dialog</property><child><placeholder/></child><child internal-child=\""
  "vbox\"><object class=\"GtkBox\" id=\"regex-dialog-vbox\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"orientation\">vertical</property><property name=\"sp"
  "acing\">2</property><child internal-child=\"action_area\"><object class"
  "=\"GtkButtonBox\" id=\"regex-dialog-actionarea\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"layout_style\">end</property><child><object class=\"GtkButto"
  "n\" id=\"regex-dialog-button-cancel\"><property name=\"label\">_Cancel<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">True</prop"
  "erty><property name=\"use_underline\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkButton\" id=\"regex-dialog-button-ok\"><propert"
  "y name=\"label\">_OK</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">True</property><property name=\"use_underline\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">1</property"
  "></packing></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">False</property><property name=\"pack_t"
  "ype\">end</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkBox\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "border_width\">6</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "Entry\" id=\"regex-entry\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"invisible_ch"
  "ar\">\342\200\242</property><property name=\"secondary_icon_stock\">gtk"
  "-apply</property></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkScrolledWindow"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"shadow_type\">in</property><child><o"
  "bject class=\"GtkViewport\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><child><object class=\"GtkT"
  "extView\" id=\"regex-textview\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"pixels_"
  "above_lines\">2</property><property name=\"pixels_below_lines\">2</prop"
  "erty><property name=\"pixels_inside_wrap\">4</property><property name=\""
  "wrap_mode\">word</property><property name=\"buffer\">textbuffer1</prope"
  "rty></object></child></object></child></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">1</property></packing></child></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child></obj"
  "ect></child><action-widgets><action-widget response=\"-6\">regex-dialog"
  "-button-cancel</action-widget><action-widget response=\"-10\">regex-dia"
  "log-button-ok</action-widget></action-widgets></object></interface>"
};

static const unsigned settings_dialog_ui_length = 44036u;

